"""make time-bounded goals

Revision ID: 8f7566ab3e16
Revises: 04e26d6557e7
Create Date: 2019-09-19 21:20:33.711253

"""
from alembic import op
import sqlalchemy as sa

import spaceship

# revision identifiers, used by Alembic.
revision = '8f7566ab3e16'
down_revision = '04e26d6557e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('hidden_after', spaceship.models.custom_fields.PendulumDateTimeField(), nullable=True))
    op.add_column('goal', sa.Column('visible_after', spaceship.models.custom_fields.PendulumDateTimeField(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'visible_after')
    op.drop_column('goal', 'hidden_after')
    # ### end Alembic commands ###
