"""add mission uuid

Revision ID: fd4d749a0aa4
Revises: 6f32f51871d2
Create Date: 2019-09-29 01:19:20.316651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4d749a0aa4'
down_revision = '6f32f51871d2'
branch_labels = None
depends_on = None

# make sure this migration will keep working *magic*
from spaceship.db import db
db.Model.metadata.bind = op.get_bind()

# imports for the data part of the migration
from spaceship.models import Mission
import uuid

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('uuid', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'mission', ['uuid'])

    for m in Mission.query.filter(Mission.uuid == None).all():
      m.uuid = uuid.uuid4().hex
      m.save()

    m.session.commit()

    op.alter_column('mission', 'uuid', nullable=False, existing_type=sa.String(length=32))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uuid', 'mission', type_='unique')
    op.drop_column('mission', 'uuid')
    # ### end Alembic commands ###
